== About Us


* Eoin Woods

* Dan Haywood

[TIP]
====
note to Eoin:

* this is draft and all is up for revision/deletion/addition etc etc.  there is too much material here, I think

* not sure if we'd be able to use this animated slide deck, or if there's a special template we need to use instead.  But I've created the deck anyway though cos (a) easier to version control and (b) is more enjoyable/rewarding to do.  Can always port to PPT/Keynote later if necessary

* press *Esc* for overview, arrow keys, *s* for speaker notes
====




[NOTE.speaker]
====
Original abstract:

* A problem all software projects encounter is making sure that code reflects the desired architectural principles/constraints. Many approaches have been tested, but the practical unification of architecture and code still eludes us.

* Apache Isis takes a different approach, forcibly separating architectural constructs from domain model, combining the two at runtime. It promises to free the developer from writing “boilerplate” and focus on the domain model instead.

* In this talk we’re going to explore these architectural issues and demonstrate how the framework addresses these.
====




== Setting the scene

* ...

* ...


[NOTE.speaker]
--
for Eoin to set the scene
--



== Assumptions/context

* we're building custom *line-of-business* applications

* these applications have *relatively complex* domain logic



[NOTE.speaker]
--
for Eoin to set the scene

* CRUD applications are just a trivial subset of the above...
--



