== About Us

* *Eoin Woods* is CTO at Endava, a European IT services company.  He is also the author of “Software Systems Architecture”

* *Dan Haywood* is an independent consultant & developer specializing in domain driven design.  He is an Apache member and PMC chair for apache.isis



[NOTE.speaker]
====
Original abstract:

* A problem all software projects encounter is making sure that code reflects the desired architectural principles/constraints. Many approaches have been tested, but the practical unification of architecture and code still eludes us.

* Apache Isis takes a different approach, forcibly separating architectural constructs from domain model, combining the two at runtime. It promises to free the developer from writing “boilerplate” and focus on the domain model instead.

* In this talk we’re going to explore these architectural issues and demonstrate how the framework addresses these.
====




== Setting the scene

* ...

* ...


[NOTE.speaker]
--
for Eoin to set the scene
--



== Assumptions/context

* we're building custom *line-of-business* applications

* these applications have *relatively complex* domain logic



[NOTE.speaker]
--
for Eoin to set the scene

* CRUD applications are just a trivial subset of the above...
--



